meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: mongod
    templates:
    - name: mongod
      release: sm-mongo
    instances: 3
    persistent_disk: 0
    resource_pool: small_z1
    networks:
      - name: sm_mongo1
        static_ips: (( static_ips(0,1,2) ))

  - name: mongodb-broker
    templates:
    - name: cf-mongodb-broker
      release: sm-mongo
    - name: route_registrar
      release: cf
    instances: 1
    persistent_disk: 0
    resource_pool: errand_pool
    networks:
      - name: sm_mongo1
        static_ips: (( static_ips(3) ))

  - name: replset
    instances: 1
    lifecycle: errand
    networks:
    - name: sm_mongo1
      static_ips: (( static_ips(4) ))
    resource_pool: errand_pool
    templates:
    - name: replset
      release: sm-mongo

  - name: register-broker
    templates:
    - name: register-broker
      release: sm-mongo
    instances: 1
    lifecycle: errand
    resource_pool: errand_pool
    networks:
      - name: sm_mongo1
        static_ips: (( static_ips(5) ))
  - name: deregister-broker
    templates:
    - name: deregister-broker
      release: sm-mongo
    instances: 1
    lifecycle: errand
    resource_pool: errand_pool
    networks:
      - name: sm_mongo1
        static_ips: (( static_ips(6) ))