---
meta:
  environment: mongodb
  security_groups: REPLACE
  stemcell:
    name: bosh-openstack-kvm-ubuntu-trusty-go_agent

director_uuid: REPLACE

releases:
  - name: sm-mongo
    version: latest
  - name: cf
    version: latest

networks:
- name: sm_mongo1
  type: manual
  subnets:
  - range: REPLACE
    cloud_properties:
      net_id: REPLACE
      security_groups:
      - REPLACE
    dns:
    - REPLACE
    gateway: REPLACE
    static:
      - REPLACE
    reserved:
      - REPLACE

properties:
  route_registrar:
    routes:
    - name: p-mongodb
      port: 80
      registration_interval: 20s
      uris:
      - p-mongodb.DOMAIN_REPLACE
  nats:
    machines:
    - REPLACE
    password: REPLACE
    port: 4222
    user: REPLACE
  mongod:
    replSet:
      enabled: true
      name: REPLICA_SET_NAME_REPLACE
      key: REPLICA_SET_KEY_MORE_THAN_4_CHARACTERS
    nodes:
      bind_ip: 0.0.0.0
      port: 27017
    path:
      log: /var/vcap/sys/log/mongod/mongod.log
    storage:
      path: /var/vcap/store/mongod
      engine: wiredTiger
      journal: true
    root:
      user: MONGODB_ROOT_USERNAME
      pass: MONGODB_ROOT_PASS
  broker:
    security_user_name: BROKER_USERNAME
    security_user_password: BROKER_PASSWORD
  cf:
    api_endpoint: REPLACE
    skip_ssl_verification: true
    user: REPLACE
    password: REPLACE
    org: REPLACE
    space: REPLACE

jobs:
  - name: mongod
    instances: 3
    persistent_disk: 10240

update:
  max_in_flight: 1
  serial: true